### ISSUE TITLE
Handling 500+ users

### ISSUE THREAD

**Issue by Jayko001** [tembo-io/clerk_fdw#2]
Current API request has a limit of 500. Will need to handle this with offset until we get all the data back.

**Comment by ryw** [comment]
Yes - we should implement the ability to use `clerk_fdw` to get user count from:
https://clerk.com/docs/reference/backend-api/tag/Users#operation/GetUsersCount 
Yes another endpoint.
And then the user can manage pagination themselves.

Does the query to users allow me to pass through `limit` `offset` and `order_by`? If not, it needs to (once we get over 500 users, which may not be long).

For organizations, they return `total_count` so the user can paginate based off that (sorta non-uniform).

**Comment by Jayko001** [comment]
https://github.com/tembo-io/clerk_fdw/pull/14
